# -*- coding: utf-8 -*-
"""Sentiment Analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xL1rS5vYRZ7vYEtwtA3MlkFiWDGM5Tjv
"""

!pip install emoji

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from google.colab import files
from os.path import exists
from os import environ, system

uploaded = files.upload()

df = pd.read_csv("sentiment_data.csv", encoding="utf-8")
df.head()

name_col = ["rownum", "Comment", "Sentiment"]

df.columns = name_col
df.columns

df.info()

df["Comment"] = df["Comment"].astype(str)

"""**Emojis and any char**"""

# checking emojies
import emoji
has_emoji = df["Comment"].apply(lambda x: any(char in emoji.EMOJI_DATA for char in x))
print(has_emoji.value_counts())

has_emojiiiii = df["Comment_no_emoji"].apply(lambda x: any(char in emoji.EMOJI_DATA for char in x))
print(has_emojiiiii.value_counts())

# converting emojis to text
df["Comment_no_emoji"] = df["Comment"].apply(lambda x: emoji.demojize(x))

# cleaning emojis format to be useable
df["Comment_no_emoji"] = df["Comment_no_emoji"].str.replace("[:_]", " ", regex=True)

# for finding all types of emojis
import re
emoji_pattern = re.compile("["
                           u"\U0001F600-\U0001F64F"  # emoticons
                           u"\U0001F300-\U0001F5FF"  # symbols
                           u"\U0001F680-\U0001F6FF"  # transport
                           u"\U0001F1E0-\U0001F1FF"  # flags
                           "]+", flags=re.UNICODE)

has_emoji_two = df["Comment_no_emoji"].apply(lambda x: bool(emoji_pattern.search(str(x))))
print(has_emoji_two.sum())

# checking for other types of emojis
print(df[has_emoji_two == True]["Comment_no_emoji"].values)

text = df[has_emoji_two == True]["Comment_no_emoji"].iloc[0]
for c in text:
    print(c, ord(c))

# deleting Regional Indicator Symbols
import re
df["Comment_no_emoji"] = df["Comment_no_emoji"].apply(
    lambda x: re.sub(r'[\U0001F1E6-\U0001F1FF]', '', x))

df.head(40)

"""**Uppercase handling**"""

# checking percewntage of uppercase and add to table
def uppercase_ratio(text):
    if len(text) == 0:
        return 0
    num_upper = sum(1 for c in text if c.isupper())
    return num_upper / len(text)

upper_ratio = df["Comment_no_emoji"].apply(uppercase_ratio)
print(upper_ratio.describe())

# it was for the time that there was a column for that
# df.value_counts("upper_ratio")

# for checking how many uppercase is in the column
# df["Comment"].str.isupper().value_counts()

# converting the uppercase to lower
df["Comment"] = df["Comment"].apply(lambda x: str(x).lower())
df["Comment"] = df["Comment"].str.lower().str.strip()
df["Comment"] = df["Comment"].astype(str).str.lower()

for text in df["Comment_no_emoji"]:
    for i in text:
        if i.isupper():
            print(repr(i))
            break

import unicodedata
def normalize_text(text):
    return unicodedata.normalize("NFKD", text)

df["Comment_lower"] = df["Comment_no_emoji"].apply(normalize_text)
df["Comment_lower"] = df["Comment_no_emoji"].str.lower().str.strip()

import re
def remove_non_latin(text):
    return re.sub(r"[^a-zA-Z0-9\s]", "", text)
df["Comment_lower"] = df["Comment_lower"].apply(remove_non_latin)

df["Comment_lower"].replace("", np.nan, inplace=True)
df.dropna(subset=["Comment_lower"], inplace=True)
df.reset_index(drop=True, inplace=True)

df.head(60)

"""**URL**"""

# checking urls
import re
has_url = df["Comment_lower"].apply(lambda x: bool(re.search(r"http[s]?://", x)))
print(has_url.value_counts())

# df["Comment"].str.contains("http").value_counts()

"""**CONTRACTIONS**"""

!pip install contractions
import contractions

# checking contractions
has_contraction = df["Comment_lower"].str.contains(r"\b\w+'\w+\b")
print(has_contraction.value_counts())

# this is for handling contractions like im that will convert to i am
df["contractions"] = df["Comment_lower"].apply(lambda x: contractions.fix(x))

apostrophes_cheker = ()
for text in df["Comment_lower"]:
    for i in text:
        if i in ["'", "’"]:
            apostrophes_cheker.add(i)
print(apostrophes_cheker)

has_contraction = df["contractions"].str.contains(r"\b\w+'\w+\b", regex=True)
print(has_contraction.sum())

# for combining all of them
# has_contraction = df["Comment"].str.contains(r"\b\w+[-']\w+\b|\b(?:don't|can't|I'm|you're)\b")

# df["Comment"].str.contains("'").value_counts()

df.head(10)

"""**-------------- -------------- -------------- --------------**

**Tokenization and stopword removal**
"""

!pip install contractions

import contractions
import nltk
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords

nltk.download('wordnet')
nltk.download('omw-1.4')
nltk.download('punkt')
nltk.download('stopwords')
nltk.download('punkt_tab')

# tokenization or splitting the word
df["tokenizing"] = df["contractions"].apply(word_tokenize)

# stopwords removal
handling_stop_words = set(stopwords.words('english'))

df["stopword_removal"] = df["tokenizing"].apply(lambda words: [w for w in words if w.lower() not in handling_stop_words])

# for the time if it needs to turn back to the text again
# df['clean_text'] = df['tokens'].apply(lambda words: ' '.join(words))

df.loc[[55, 56, 57, 58, 59, 60, 61]]

df.head(10)

"""**Lemmatization**"""

# a kind of NLTK way
df["Lemmatization"] = df["stopword_removal"].apply(
    lambda words: [word for word in words if word not in handling_stop_words])

# spaCy way
import spacy
nlp = spacy.load("en_core_web_sm")

def lemmatizing(text):
    mydocument = nlp(text)
    return " ".join([token.lemma_ for token in mydocument])

df["Lemmatization"] = df["stopword_removal"].apply(lemmatizing)

def lemmatizing(text):
    if isinstance(text, list):
        text = " ".join(text)
    mydocument = nlp(text)
    return " ".join([token.lemma_ for token in mydocument])

df["Lemmatization"] = df["stopword_removal"].apply(lemmatizing)

# NLTK way
from nltk.stem import WordNetLemmatizer
lemmatizer = WordNetLemmatizer()

df["Lemmatization"] = df["stopword_removal"].apply(lambda words: [lemmatizer.lemmatize(w) for w in words])
df["lemmatized_text"] = df["Lemmatization"].apply(lambda words: ' '.join(words))

df.head(10)

"""**Create CSV file**"""

df.to_csv("prepared_sentiment_data.csv", index=False)

dff = pd.read_csv("/content/prepared_sentiment_data.csv")
dff.head()

dff.drop(columns=["Comment_no_emoji", "Comment_lower", "contractions",
"tokenizing", "stopword_removal", "Lemmatization"], inplace=True)
dff

dff["lemmatized_text"].replace("", np.nan, inplace=True)
dff.dropna(subset=["lemmatized_text"], inplace=True)
dff.reset_index(drop=True, inplace=True)

dff.to_csv("prepared_sentiment_data_less_column.csv", index=False)

